import {LogIn,LogOut,UserRound} from 'lucide-react'
import {useEffect,useRef,useState} from 'react'
import {api} from '../lib/api'

type AuthUser={id:number;email:string;name:string;picture?:string}
declare global{interface Window{google?:{accounts:{id:{initialize:(options:{client_id:string;callback:(response:{credential:string})=>void})=>void;renderButton:(element:HTMLElement,options:Record<string,unknown>)=>void;prompt:()=>void}}}}}

export default function GoogleAuth(){const [user,setUser]=useState<AuthUser|null>(null),[open,setOpen]=useState(false),[error,setError]=useState(''),button=useRef<HTMLDivElement>(null);const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID as string|undefined
 useEffect(()=>{void api.me().then(x=>{if(x.authenticated&&x.user)setUser(x.user)}).catch(()=>{})},[])
 useEffect(()=>{const openAuth=()=>setOpen(true);window.addEventListener('manaksetu-open-auth',openAuth);return()=>window.removeEventListener('manaksetu-open-auth',openAuth)},[])
 useEffect(()=>{if(!open||!clientId)return;const init=()=>{if(!window.google||!button.current)return;window.google.accounts.id.initialize({client_id:clientId,callback:async({credential})=>{try{const result=await api.googleAuth(credential);localStorage.setItem('manaksetu-token',result.token);setUser(result.user);setOpen(false);setError('');window.dispatchEvent(new CustomEvent('manaksetu-auth-changed',{detail:result.user}))}catch(exc){setError(exc instanceof Error?exc.message:'Sign-in failed')}}});button.current.innerHTML='';window.google.accounts.id.renderButton(button.current,{theme:'outline',size:'large',shape:'pill',width:300})};if(window.google){init();return}const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=init;document.head.appendChild(script)},[open,clientId])
 async function logout(){try{await api.logout()}finally{localStorage.removeItem('manaksetu-token');setUser(null);window.dispatchEvent(new CustomEvent('manaksetu-auth-changed'))}}
 if(user)return <div className="user-menu"><span className="user-avatar"><UserRound/></span><span><strong>{user.name}</strong><small>{user.email}</small></span><button onClick={logout} aria-label="Sign out"><LogOut/></button></div>
 return <><button className="sign-in-button" onClick={()=>setOpen(true)}><LogIn/> Sign in</button>{open&&<div className="auth-backdrop" onClick={()=>setOpen(false)}><section className="auth-modal" role="dialog" aria-modal="true" aria-labelledby="auth-title" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setOpen(false)} aria-label="Close">×</button><img className="auth-logo" src="/assets/bis-logo-strip.png" alt="Bureau of Indian Standards"/><h2 id="auth-title">Welcome to BIS ManakSathi AI</h2><p>Sign in to save conversations and continue your standards journey across devices.</p>{clientId?<div className="google-button-wrap" ref={button}/>:<div className="auth-config"><strong>Google sign-in needs configuration</strong><span>Add the same OAuth Web Client ID to <code>GOOGLE_CLIENT_ID</code> and <code>VITE_GOOGLE_CLIENT_ID</code>, then restart both servers.</span></div>}{error&&<p className="auth-error" role="alert">{error}</p>}<small>Independent demo—not an official BIS portal. We never receive your Google password.</small></section></div>}</>}
