from datetime import date
from django.core.management.base import BaseCommand
from django.db import transaction
from core.models import (ApplicationGuide, ApplicationStep, CertificationRecord, DocumentChunk,
                         SafetyAlert, SourceDocument, StandardRecord)
from core.services.chunking import chunk_text

STANDARDS = [
    {"number":"IS 367:1993","equivalent":"IEC 60530","title":"Electric kettles and jugs for household and similar use — Specification (Fourth Revision)","aspect":"Product Specification","department":"ETD (Electrotechnical Department)","committee":"ETD 32 (Electrical Appliances Sectional Committee)","secretary":"Ankita Tripathi (SCIENTIST-D)","revisions":4,"scope":"This standard covers general, safety and performance requirements for electric kettles, jugs and similar household appliances having a rated capacity not exceeding 5 litres and supplies not exceeding 250 V AC single phase or DC. It excludes electrode heating appliances, sterilizers, coffee percolators, immersion heaters and storage water heaters."},
    {"number":"IS 11676:1995","equivalent":"IEC 60705","title":"Microwave ovens for household and similar purposes — Specification (First Revision)","aspect":"Product Specification","department":"ETD (Electrotechnical Department)","committee":"ETD 32 (Electrical Appliances Sectional Committee)","secretary":"Ankita Tripathi (SCIENTIST-D)","scope":"Covers general, safety and performance requirements and test methods for household and similar microwave ovens connected to supplies not exceeding 250 V AC single phase, 50 Hz, together with applicable provisions of IS 302-2-25."},
    {"number":"IS 1649:1962","title":"Code of practice for design and construction of flues and chimneys for domestic heating appliances","aspect":"Code of Practice","department":"CED (Civil Engineering Department)","committee":"CED 13 (Building Construction Practices Sectional Committee)","secretary":"Nakkala Praveen Sai (SCIENTIST-B)","revisions":1,"equivalence":"Indigenous","scope":"Deals with design and construction of naturally-draught flues and chimneys for domestic appliances, made from masonry, cast in-situ concrete, terracotta or metal pipe, subject to stated heat ranges."},
    {"number":"IS 302 (Part 2/Sec 24):1994","equivalent":"IEC 60335-2-24","title":"Safety of household and similar electrical appliances: refrigerators, food-freezers and ice-makers","aspect":"Safety Standard","department":"MED (Mechanical Engineering Department)","committee":"MED 03 (Refrigeration and Air Conditioning Sectional Committee)","secretary":"Neha Thakur (SCIENTIST-C)","scope":"Applies to electrical refrigerators, frozen-food cabinets, food freezers, combinations and certain ice-makers for household and similar use. It covers safety, not separate construction and operational performance requirements, and excludes appliances exclusively for industrial or special hazardous locations."},
    {"number":"IS 12575:2010","title":"Fried potato chips — Specification (First Revision)","aspect":"Product Specification","department":"FAD (Food and Agriculture Department)","committee":"FAD 16 (Foodgrains, Allied Products and Ready-to-Eat Foods Sectional Committee)","secretary":"Abhijit Singh (SCIENTIST-C)","equivalence":"Indigenous","scope":"Prescribes requirements and methods of sampling and test for fried potato chips, with normative references for food hygiene, sampling, salt and permitted food-grade ingredients."},
    {"number":"IS 15893:2011","equivalent":"ISO 10713:1992","title":"Jewellery — Gold alloy coatings","aspect":"Product Specification","department":"MTD (Metallurgical Engineering Department)","committee":"MTD 10 (Precious Metals Sectional Committee)","secretary":"Ajay Kumar Soni (SCIENTIST-C)","equivalence":"Identical under dual numbering","scope":"Specifies requirements relating to gold alloy coatings used on jewellery."},
    {"number":"IS 15748:2022","equivalent":"ISO 11612:2015","title":"Protective clothing — Clothing to protect against heat and flame — Minimum performance requirements","aspect":"Product Specification","department":"TXD (Textiles Department)","committee":"TXD 32 (Textiles Protective Clothing Sectional Committee)","secretary":"Mayur Katiyar (SCIENTIST-C)","revisions":1,"amendments":3,"supersedes":"IS 15748:2007","equivalence":"Identical under dual numbering","scope":"Minimum performance requirements for clothing protecting industrial workers against heat and flame. The revision aligns the Indian Standard with ISO 11612:2015 and excludes specialist firefighter and welder clothing where separately addressed."},
    {"number":"IS 2994:1992","title":"Electric stoves — Specification (Second Revision)","aspect":"Product Specification","department":"ETD (Electrotechnical Department)","committee":"ETD 32 (Electrical Appliances Sectional Committee)","secretary":"Ankita Tripathi (SCIENTIST-D)","revisions":2,"scope":"Covers general safety and performance requirements and tests for electric stoves with open heating elements for supplies up to 250 V AC single phase 50 Hz or DC. Multi-unit stoves are excluded."},
    {"number":"IS 2347:2023","title":"Domestic pressure cooker — Specification (Seventh Revision)","aspect":"Product Specification","department":"MED (Mechanical Engineering Department)","committee":"MED 33 (Utensils, Cutlery and Domestic Hardware Sectional Committee)","secretary":"Neha Thakur (SCIENTIST-C)","revisions":7,"equivalence":"Indigenous","scope":"Covers requirements for domestic pressure cookers. Microwaveable pressure cookers are outside its scope."},
    {"number":"IS 14155:2025","title":"Domestic electric clothes washing machines for household use — Specification (First Revision)","aspect":"Product Specification","department":"ETD (Electrotechnical Department)","committee":"ETD 32 (Electrical Appliances Sectional Committee)","secretary":"Ankita Tripathi (SCIENTIST-D)","revisions":1,"supersedes":"IS 14155:1994","scope":"Covers performance requirements and test methods for domestic washing machines, spin extractors and washer-dryers. It does not cover commercial laundries or acoustic-noise requirements; safety is addressed in relevant parts of IS 302."},
    {"number":"IS 6721:2023","title":"Sandals and slippers — Specification (First Revision)","aspect":"Product Specification","department":"CHD (Chemical Department)","committee":"CHD 19 (Footwear Sectional Committee)","secretary":"Vikas Agrawal (SCIENTIST-C)","revisions":1,"equivalence":"Indigenous","scope":"Prescribes characteristics, requirements and methods of sampling and test for all varieties of sandals and slippers, whether fully moulded or assembled."},
    {"number":"IS 6356:2021","title":"Toothpaste — Specification","aspect":"Product Specification","department":"PCD (Petroleum, Coal and Related Products Department)","committee":"PCD 19 (Cosmetics Sectional Committee)","secretary":"Shivam Dwivedi (SCIENTIST-C)","revisions":4,"amendments":1,"equivalence":"Indigenous","scope":"Prescribes requirements and methods of sampling and test for toothpaste, including referenced methods for cosmetic sampling, microbiological examination, safety evaluation and heavy-metal determination."},
    {"number":"IS 10902:2022","title":"Protein-rich (Paushtik) maida — Specification (First Revision)","aspect":"Product Specification","department":"FAD (Food and Agriculture Department)","committee":"FAD 16 (Foodgrains, Allied Products and Ready-to-Eat Foods Sectional Committee)","secretary":"Abhijit Singh (SCIENTIST-C)","revisions":1,"equivalence":"Indigenous","scope":"Prescribes requirements and methods of sampling and test for protein-rich (paushtik) maida, with references covering maida, atta, food hygiene, edible soya flour, packaging and aflatoxin testing."},
    {"number":"IS/ISO 11114-4:2017","equivalent":"ISO 11114-4:2017","title":"Transportable gas cylinders — Compatibility of cylinder and valve materials with gas contents — Part 4","aspect":"Methods of tests","department":"MED (Mechanical Engineering Department)","committee":"MED 16 (Gas Cylinders Sectional Committee)","secretary":"Prasoon Yadav (SCIENTIST-C)","revisions":1,"equivalence":"Identical under single numbering","scope":"Specifies test methods for selecting steels resistant to hydrogen embrittlement for transportable gas cylinders and valve materials. It is Part 4 of the compatibility series."},
]

class Command(BaseCommand):
    help = "Seed clearly-labelled demo standards, verification, guide and safety data."

    @transaction.atomic
    def handle(self, *args, **options):
        for index, item in enumerate(STANDARDS, 1):
            doc, _ = SourceDocument.objects.update_or_create(document_id=f"DEMO-STD-{index:03}", version=1, defaults={
                "title": item["title"], "standard_number": item["number"], "source_type":"demo", "category":item["department"].split(" ")[0],
                "content": item["scope"], "language":"en"})
            DocumentChunk.objects.filter(document=doc).delete()
            for chunk in chunk_text(f"1 SCOPE\n{item['scope']}"):
                DocumentChunk.objects.create(document=doc, chunk_index=chunk.index, section=chunk.section or "1 Scope", text=chunk.text, token_count=len(chunk.text.split()), metadata={"fixture":"user-supplied-demo"})
            StandardRecord.objects.update_or_create(number=item["number"], defaults={"title":item["title"], "equivalent_standard":item.get("equivalent", ""), "supersedes":item.get("supersedes", ""), "equivalence":item.get("equivalence", "Modified/Technically Equivalent"), "revision_count":item.get("revisions", 0), "amendment_count":item.get("amendments", 0), "aspect":item["aspect"], "department":item["department"], "committee":item["committee"], "member_secretary":item["secretary"], "scope":item["scope"], "source_document":doc, "is_demo":True})
        CertificationRecord.objects.update_or_create(identifier="CM/L-1234567890", defaults={"status":"active", "organization":"Setu Home Appliances Pvt. Ltd.", "product_scope":"Domestic pressure cookers", "standard_number":"IS 2347:2023", "issue_date":date(2025,4,1), "expiry_date":date(2027,3,31), "is_demo":True})
        CertificationRecord.objects.update_or_create(identifier="R-98765432", defaults={"identifier_type":"registration", "status":"expired", "organization":"Demo Electronics India", "product_scope":"Microwave ovens", "standard_number":"IS 11676:1995", "issue_date":date(2022,1,1), "expiry_date":date(2024,12,31), "is_demo":True})
        guide, _ = ApplicationGuide.objects.update_or_create(slug="isi-product-certification", defaults={"title":"ISI product certification journey", "summary":"A demo, step-by-step preparation guide for manufacturers.", "scheme":"Product Certification Scheme-I", "is_demo":True})
        steps = [(1,"Confirm the applicable standard","Describe the product and confirm the relevant Indian Standard before applying.",["Product description and variants","Manufacturing location","Candidate Indian Standard"]), (2,"Prepare documents","Collect organization, manufacturing and quality-control records.",["Business registration","Factory layout","Manufacturing process flow","Testing equipment list","Quality-control personnel details"]), (3,"Submit the application","Use the official BIS portal and retain the application reference.",["Completed online application","Applicable fee receipt","Supporting documents"]), (4,"Factory evaluation and product testing","Prepare for evaluation and sampling through recognized processes.",["Working test equipment","Calibration records","Raw-material controls","Sample availability"]), (5,"Decision and ongoing compliance","Review the licence scope and maintain surveillance readiness.",["Licence scope verification","Marking controls","Periodic testing records","Renewal calendar"])]
        ApplicationStep.objects.filter(guide=guide).delete()
        for order,title,description,checklist in steps:
            ApplicationStep.objects.create(guide=guide, order=order, title=title, description=description, checklist=checklist, estimated_next_step="Confirm current requirements and timelines on the official BIS portal.", links=[{"label":"BIS official website","url":"https://www.bis.gov.in/"}])
        SafetyAlert.objects.update_or_create(title="Demo safety notice: inspect pressure-cooker safety components", defaults={"summary":"Sample educational alert: stop using a cooker if its safety valve, gasket or lid-locking mechanism is damaged. This is not a current official recall.","severity":"warning","is_demo":True,"active":True})
        self.stdout.write(self.style.SUCCESS(f"Seeded {len(STANDARDS)} standards and demo journeys."))

