# Generated by Django 5.2.17 on 2026-09-05 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField()),
                ("scheme", models.CharField(db_index=True, max_length=120)),
                ("language", models.CharField(default="en", max_length=12)),
                ("is_demo", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CertificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("identifier_type", models.CharField(default="licence", max_length=30)),
                ("status", models.CharField(db_index=True, max_length=30)),
                ("organization", models.CharField(max_length=300)),
                ("product_scope", models.CharField(max_length=500)),
                ("standard_number", models.CharField(blank=True, max_length=120)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("section", models.CharField(blank=True, max_length=300)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("text", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("vector_id", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_label", models.CharField(max_length=100)),
                ("question", models.TextField()),
                ("expected_source", models.CharField(blank=True, max_length=120)),
                ("metrics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=20),
                ),
                ("source_path", models.CharField(max_length=500)),
                ("documents_seen", models.PositiveIntegerField(default=0)),
                ("chunks_created", models.PositiveIntegerField(default=0)),
                ("failed_records", models.JSONField(blank=True, default=list)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField()),
                ("severity", models.CharField(default="info", max_length=20)),
                ("source_url", models.URLField(blank=True)),
                ("is_demo", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "title",
                    models.CharField(
                        default="New standards conversation", max_length=200
                    ),
                ),
                ("audience", models.CharField(default="industry", max_length=20)),
                ("language", models.CharField(default="en", max_length=12)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("intent", models.CharField(blank=True, db_index=True, max_length=60)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("abstained", models.BooleanField(default=False)),
                ("trace", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chatsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                ("ordinal", models.PositiveIntegerField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="core.chatmessage",
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.documentchunk",
                    ),
                ),
            ],
            options={
                "ordering": ["ordinal"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.SmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("document_id", models.CharField(max_length=120)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=500)),
                (
                    "standard_number",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("demo", "Demo fixture"),
                            ("official", "Official public source"),
                            ("user", "User supplied"),
                        ],
                        db_index=True,
                        default="demo",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "language",
                    models.CharField(db_index=True, default="en", max_length=12),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("content", models.TextField()),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category", "language"],
                        name="core_source_categor_3fbb09_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_id", "version"),
                        name="unique_document_version",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chunks",
                to="core.sourcedocument",
            ),
        ),
        migrations.CreateModel(
            name="StandardRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("equivalent_standard", models.CharField(blank=True, max_length=120)),
                ("supersedes", models.CharField(blank=True, max_length=120)),
                ("equivalence", models.CharField(blank=True, max_length=100)),
                ("revision_count", models.PositiveIntegerField(default=0)),
                ("amendment_count", models.PositiveIntegerField(default=0)),
                ("aspect", models.CharField(db_index=True, max_length=100)),
                (
                    "language",
                    models.CharField(db_index=True, default="en", max_length=12),
                ),
                ("department", models.CharField(db_index=True, max_length=200)),
                ("committee", models.CharField(blank=True, max_length=300)),
                ("member_secretary", models.CharField(blank=True, max_length=200)),
                ("scope", models.TextField()),
                ("is_demo", models.BooleanField(default=True)),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.sourcedocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApplicationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("checklist", models.JSONField(default=list)),
                ("links", models.JSONField(default=list)),
                ("estimated_next_step", models.CharField(blank=True, max_length=300)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.applicationguide",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guide", "order"), name="unique_guide_step"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("document", "chunk_index"), name="unique_document_chunk"
            ),
        ),
    ]
