# Generated by Django 5.2.17 on 2026-09-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
